# Generated by Django 5.0.6 on 2024-07-19 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_passenger_user'),
        ('trip', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Payed', 'Payed'), ('Expired', 'Expired')], default='Booked', max_length=8)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='trip.Trip')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_num', models.IntegerField()),
                ('place_floor', models.IntegerField()),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.passenger')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_tickets', to='books.ticket')),
            ],
        ),
    ]
