# Generated by Django 5.0.6 on 2024-08-26 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_ticketpassenger_user_alter_ticketpassenger_passenger_and_more'),
        ('trip', '0002_trip_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='trip.trip'),
        ),
    ]
