# Generated by Django 5.0.6 on 2024-09-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_ticket_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Payed', 'Payed'), ('Expired', 'Expired'), ('Refunded', 'Refunded')], default='Booked', max_length=8),
        ),
    ]
