# Generated by Django 5.0.6 on 2024-09-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Payed', 'Payed'), ('Expired', 'Expired')], default='Booked', max_length=8),
        ),
    ]
