# Generated by Django 5.0.6 on 2024-09-29 19:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_ticket_booked_at_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpassenger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
