# Generated by Django 5.0.6 on 2024-07-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_alter_customuser_managers_remove_customuser_username_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="дата рождения"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="document_number_or_iin",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="номер документа или ИИН",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="document_type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="тип документа"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="электронная почта",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ФИО"
            ),
        ),
    ]
