# Generated by Django 5.0.6 on 2024-07-04 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_birth_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="ФИО пассажира"),
                ),
                (
                    "document_type",
                    models.CharField(max_length=50, verbose_name="тип документа"),
                ),
                (
                    "document_number_or_iin",
                    models.CharField(
                        max_length=100, verbose_name="номер документа или ИИН"
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="дата рождения")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passengers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
