# Generated by Django 5.0.6 on 2024-09-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='is_profile_passenger',
            field=models.BooleanField(default=False),
        ),
    ]
