# Generated by Django 5.0.6 on 2024-08-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='id',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
