# Generated by Django 5.0.6 on 2024-08-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_v2', '0002_alter_stop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
