# Generated by Django 5.0.6 on 2024-08-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_v2', '0003_alter_stop_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
            ],
        ),
    ]
