# Generated by Django 5.0.6 on 2024-08-27 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_v2', '0004_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='end_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_routes', to='trip_v2.city'),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_routes', to='trip_v2.city'),
        ),
    ]
