# Generated by Django 5.0.6 on 2024-07-03 09:09

import buses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.CharField(default=buses.models.generate_bus_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('direction', models.CharField(max_length=255)),
                ('count_of_seats', models.PositiveIntegerField()),
                ('have_toilet', models.BooleanField(default=False)),
                ('have_wifi', models.BooleanField(default=False)),
                ('is_recumbent', models.BooleanField(default=False)),
            ],
        ),
    ]
