# Generated by Django 5.0.6 on 2024-07-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='floors',
            field=models.PositiveIntegerField(choices=[(1, 'One'), (2, 'Two')], default=1),
        ),
    ]
