# Generated by Django 5.0.6 on 2024-07-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_bus_floors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='direction',
        ),
    ]
