# Generated by Django 5.0.6 on 2024-08-12 03:58

import buses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_remove_bus_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='VIN',
            field=models.CharField(default=123, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='name',
            field=models.CharField(default='dasldjkasda', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='scheme',
            field=models.FileField(blank=True, null=True, upload_to=buses.models.bus_scheme_upload_to),
        ),
        migrations.AddField(
            model_name='bus',
            name='state_number',
            field=models.CharField(default='114 eya 02', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='buses.model'),
        ),
        migrations.AddField(
            model_name='model',
            name='stamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='buses.stamp'),
        ),
        migrations.AddField(
            model_name='bus',
            name='stamp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='buses.stamp'),
        ),
    ]
