# Generated by Django 5.0.6 on 2024-08-12 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_model_stamp_bus_vin_bus_name_bus_scheme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='stamp',
        ),
    ]
