# Generated by Django 5.0.6 on 2024-08-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0005_remove_model_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='VIN',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='state_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
