# Generated by Django 5.0.6 on 2024-08-12 04:17

import buses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0006_alter_bus_vin_alter_bus_state_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=buses.models.driver_picture_upload_to)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('license_number', models.CharField(max_length=20, unique=True)),
                ('license_issue_date', models.DateField()),
            ],
        ),
    ]
