# Generated by Django 5.0.6 on 2024-08-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0007_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='VIN',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='bus',
            name='state_number',
            field=models.CharField(max_length=10),
        ),
    ]
