# Generated by Django 5.0.6 on 2024-09-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0008_alter_bus_vin_alter_bus_state_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
