# Generated by Django 5.0.6 on 2024-09-29 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0008_alter_bus_vin_alter_bus_state_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_id', models.PositiveIntegerField()),
                ('seat_col', models.PositiveIntegerField()),
                ('seat_row', models.PositiveIntegerField()),
                ('seat_type', models.CharField(choices=[('aisle', 'Aisle'), ('passenger', 'Passenger'), ('driver', 'Driver')], max_length=50)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='buses.bus')),
            ],
        ),
    ]
