# Generated by Django 5.0.6 on 2024-08-22 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0008_alter_bus_vin_alter_bus_state_number'),
        ('trip_v2', '0003_alter_stop_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(max_length=255)),
                ('weekdays', models.JSONField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='buses.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='buses.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trip_v2.route')),
            ],
        ),
    ]
