# Generated by Django 5.0.6 on 2024-08-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
