# Generated by Django 5.0.6 on 2024-08-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_trip_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='active',
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('active', 'Рейс активен, идут продажи'), ('not_on_sale', 'Рейс не в продаже'), ('cancelled', 'Рейс отменен'), ('scheduled', 'с {start_date} по {end_date}')], default='scheduled', max_length=20),
        ),
    ]
