# Generated by Django 5.0.6 on 2024-07-03 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BusStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_datetime', models.DateTimeField()),
                ('to_datetime', models.DateTimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.bus')),
                ('from_bus_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='trips.busstation')),
                ('to_bus_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='trips.busstation')),
                ('from_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='trips.point')),
                ('to_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='trips.point')),
            ],
        ),
        migrations.AddField(
            model_name='busstation',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.point'),
        ),
    ]
