# Generated by Django 5.0.6 on 2024-07-03 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_remove_bus_direction'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buses.bus'),
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
